### ISSUE TITLE
While Start Background service got Exception Service cannot be started. Quartz.SchedulerConfigException: Failure occurred during job recovery

### ISSUE THREAD

**Issue by softtechinfo2020** [baseeam/baseeam-background-service#2]
Service cannot be started. Quartz.SchedulerConfigException: Failure occurred during job recovery. ---> Quartz.JobPersistenceException: Couldn't store trigger 'DEFAULT.ebe6129f-0596-4588-9975-847a5105e91e' for 'BackgroundJob.SendMessageJob' job: Couldn't retrieve job: Binary stream '0' does not contain a valid BinaryHeader. Possible causes are invalid stream or object version change between serialization and deserialization. ---> Quartz.JobPersistenceException: Couldn't retrieve job: Binary stream '0' does not contain a valid BinaryHeader. Possible causes are invalid stream or object version change between serialization and deserialization. ---> System.Runtime.Serialization.SerializationException: Binary stream '0' does not contain a valid BinaryHeader. Possible causes are invalid stream or object version change between serialization and deserialization.
   at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.Run()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __Bin...

**Comment by nguyencongle** [comment]
Did you get the web app run, so I can be sure you have setup the DB correctly?

**Comment by softtechinfo2020** [comment]
Yes My web App is running Correctly
![WebApp](https://user-images.githubusercontent.com/58630781/70505267-94bbf880-1b4d-11ea-849e-8ca5a2b730ea.png)

**Comment by nguyencongle** [comment]
I think we have a bug in BackgroundService, In Program.cs ConfigureContainer, we are hardcoding a connection string. You can change it to yours, but you have to build the code again.
Please let me know if you don't want to change it.

**Comment by softtechinfo2020** [comment]
Yes I changed hard coded connection string also.still had same problem.please help me

**Comment by nguyencongle** [comment]
In the database, you will see the tables with prefix QZT of quarts.net, you can clean all data in these tables and start service again.

**Comment by softtechinfo2020** [comment]
thanks for your support. now Background service running successfully.
